name: Meta Files Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Meta files check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Install the Unity Meta Check tool
          wget https://github.com/dwalton3/unity-meta-check/releases/download/v2.3.0/unity-meta-check.phar
          chmod +x unity-meta-check.phar
          sudo mv unity-meta-check.phar /usr/local/bin/unity-meta-check

          # Run the Unity Meta Check tool
          unity-meta-check --fix --safe_directories "Assets"
      - uses: DeNA/unity-meta-check@v3
        with:
          enable_pr_comment: true
          pr_comment_lang: en
          pr_comment_send_success: false
          pr_comment_pull_number: 0
          log_level: INFO
          target_path: .
          target_type: auto-detect
          ignore_dangling: false
          ignore_case: false
          ignore_submodules_and_nested: false
          enable_autofix: false
          enable_junit: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
