name: Meta Files Check
on: pull_request

jobs:
  unity-meta-check:
#    env:
#        GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeNA/unity-meta-check@v3
        with:
          enable_pr_comment: true
          pr_comment_lang: en
          pr_comment_send_success: false
