name: Meta Files Check
on: pull_request

jobs:
  unity-meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeNA/unity-meta-check@v3
        with:
          enable_pr_comment: true
          pr_comment_lang: en
          pr_comment_send_success: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
